old_sound_rabbit_mq:
    connections:
        default:
#            url: '%env(RABBITMQ_URL)%'
            host:        'localhost'
            port:        5672
            user:        'guest'
            password:    'guest'
            vhost:       '/'
            lazy:        true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        task:
            class: App\Rabbit\MessagingProducer
            connection:       default
            exchange_options: { name: 'task', type: 'topic' }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
